// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TrashItem {
  final String id;
  final String transactionId;
  final String originalPath;
  final String trashPath;
  final String filename;
  final String timestamp;

  const TrashItem({
    required this.id,
    required this.transactionId,
    required this.originalPath,
    required this.trashPath,
    required this.filename,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      transactionId.hashCode ^
      originalPath.hashCode ^
      trashPath.hashCode ^
      filename.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrashItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          transactionId == other.transactionId &&
          originalPath == other.originalPath &&
          trashPath == other.trashPath &&
          filename == other.filename &&
          timestamp == other.timestamp;
}
