// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Config {
  final String? libraryPath;
  final String? watchPath;
  final String tmdbApiKey;
  final String opensubsApiKey;
  final String tvdbApiKey;
  final List<String> subtitleLanguages;
  final bool autoDownloadSubs;
  final QbitConfig qbittorrent;
  final bool qbitEnabled;
  final bool watcherEnabled;
  final String theme;

  const Config({
    this.libraryPath,
    this.watchPath,
    required this.tmdbApiKey,
    required this.opensubsApiKey,
    required this.tvdbApiKey,
    required this.subtitleLanguages,
    required this.autoDownloadSubs,
    required this.qbittorrent,
    required this.qbitEnabled,
    required this.watcherEnabled,
    required this.theme,
  });

  @override
  int get hashCode =>
      libraryPath.hashCode ^
      watchPath.hashCode ^
      tmdbApiKey.hashCode ^
      opensubsApiKey.hashCode ^
      tvdbApiKey.hashCode ^
      subtitleLanguages.hashCode ^
      autoDownloadSubs.hashCode ^
      qbittorrent.hashCode ^
      qbitEnabled.hashCode ^
      watcherEnabled.hashCode ^
      theme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          libraryPath == other.libraryPath &&
          watchPath == other.watchPath &&
          tmdbApiKey == other.tmdbApiKey &&
          opensubsApiKey == other.opensubsApiKey &&
          tvdbApiKey == other.tvdbApiKey &&
          subtitleLanguages == other.subtitleLanguages &&
          autoDownloadSubs == other.autoDownloadSubs &&
          qbittorrent == other.qbittorrent &&
          qbitEnabled == other.qbitEnabled &&
          watcherEnabled == other.watcherEnabled &&
          theme == other.theme;
}

class QbitConfig {
  final String host;
  final int port;
  final String username;
  final String password;
  final bool autoRemove;

  const QbitConfig({
    required this.host,
    required this.port,
    required this.username,
    required this.password,
    required this.autoRemove,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      autoRemove.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QbitConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          autoRemove == other.autoRemove;
}
