// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Serializable format option for the review UI's dropdowns.
class FormatOption {
  final String name;
  final List<String> genres;

  const FormatOption({required this.name, required this.genres});

  @override
  int get hashCode => name.hashCode ^ genres.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatOption &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          genres == other.genres;
}
