// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ai_api.dart';
import 'api/config_api.dart';
import 'api/history_api.dart';
import 'api/init_api.dart';
import 'api/library_api.dart';
import 'api/pipeline_api.dart';
import 'api/playback_api.dart';
import 'api/qbit_api.dart';
import 'api/review_api.dart';
import 'api/simple.dart';
import 'api/subtitle_api.dart';
import 'api/watcher_api.dart';
import 'config.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'formats.dart';
import 'frb_generated.dart';
import 'metadata.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'pipeline.dart';
import 'qbittorrent.dart';
import 'transaction.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Config dco_decode_box_autoadd_config(dynamic raw);

  @protected
  EditRequest dco_decode_box_autoadd_edit_request(dynamic raw);

  @protected
  QbitConfig dco_decode_box_autoadd_qbit_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WatchProgress dco_decode_box_autoadd_watch_progress(dynamic raw);

  @protected
  ClearResult dco_decode_clear_result(dynamic raw);

  @protected
  Config dco_decode_config(dynamic raw);

  @protected
  EditRequest dco_decode_edit_request(dynamic raw);

  @protected
  ExternalSubtitle dco_decode_external_subtitle(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FormatInfo dco_decode_format_info(dynamic raw);

  @protected
  FormatOption dco_decode_format_option(dynamic raw);

  @protected
  GenreInfo dco_decode_genre_info(dynamic raw);

  @protected
  GenrePage dco_decode_genre_page(dynamic raw);

  @protected
  HistoryPage dco_decode_history_page(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ExternalSubtitle> dco_decode_list_external_subtitle(dynamic raw);

  @protected
  List<FormatInfo> dco_decode_list_format_info(dynamic raw);

  @protected
  List<FormatOption> dco_decode_list_format_option(dynamic raw);

  @protected
  List<GenreInfo> dco_decode_list_genre_info(dynamic raw);

  @protected
  List<MediaFile> dco_decode_list_media_file(dynamic raw);

  @protected
  List<MediaInfo> dco_decode_list_media_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TmdbMatch> dco_decode_list_tmdb_match(dynamic raw);

  @protected
  List<TorrentInfo> dco_decode_list_torrent_info(dynamic raw);

  @protected
  List<Transaction> dco_decode_list_transaction(dynamic raw);

  @protected
  List<WatchProgress> dco_decode_list_watch_progress(dynamic raw);

  @protected
  MediaDetail dco_decode_media_detail(dynamic raw);

  @protected
  MediaFile dco_decode_media_file(dynamic raw);

  @protected
  MediaInfo dco_decode_media_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  WatchProgress? dco_decode_opt_box_autoadd_watch_progress(dynamic raw);

  @protected
  QbitConfig dco_decode_qbit_config(dynamic raw);

  @protected
  QbitTestResult dco_decode_qbit_test_result(dynamic raw);

  @protected
  TmdbMatch dco_decode_tmdb_match(dynamic raw);

  @protected
  TorrentInfo dco_decode_torrent_info(dynamic raw);

  @protected
  Transaction dco_decode_transaction(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UndoBatchResult dco_decode_undo_batch_result(dynamic raw);

  @protected
  UndoResult dco_decode_undo_result(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WatchProgress dco_decode_watch_progress(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Config sse_decode_box_autoadd_config(SseDeserializer deserializer);

  @protected
  EditRequest sse_decode_box_autoadd_edit_request(SseDeserializer deserializer);

  @protected
  QbitConfig sse_decode_box_autoadd_qbit_config(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WatchProgress sse_decode_box_autoadd_watch_progress(
    SseDeserializer deserializer,
  );

  @protected
  ClearResult sse_decode_clear_result(SseDeserializer deserializer);

  @protected
  Config sse_decode_config(SseDeserializer deserializer);

  @protected
  EditRequest sse_decode_edit_request(SseDeserializer deserializer);

  @protected
  ExternalSubtitle sse_decode_external_subtitle(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FormatInfo sse_decode_format_info(SseDeserializer deserializer);

  @protected
  FormatOption sse_decode_format_option(SseDeserializer deserializer);

  @protected
  GenreInfo sse_decode_genre_info(SseDeserializer deserializer);

  @protected
  GenrePage sse_decode_genre_page(SseDeserializer deserializer);

  @protected
  HistoryPage sse_decode_history_page(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ExternalSubtitle> sse_decode_list_external_subtitle(
    SseDeserializer deserializer,
  );

  @protected
  List<FormatInfo> sse_decode_list_format_info(SseDeserializer deserializer);

  @protected
  List<FormatOption> sse_decode_list_format_option(
    SseDeserializer deserializer,
  );

  @protected
  List<GenreInfo> sse_decode_list_genre_info(SseDeserializer deserializer);

  @protected
  List<MediaFile> sse_decode_list_media_file(SseDeserializer deserializer);

  @protected
  List<MediaInfo> sse_decode_list_media_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TmdbMatch> sse_decode_list_tmdb_match(SseDeserializer deserializer);

  @protected
  List<TorrentInfo> sse_decode_list_torrent_info(SseDeserializer deserializer);

  @protected
  List<Transaction> sse_decode_list_transaction(SseDeserializer deserializer);

  @protected
  List<WatchProgress> sse_decode_list_watch_progress(
    SseDeserializer deserializer,
  );

  @protected
  MediaDetail sse_decode_media_detail(SseDeserializer deserializer);

  @protected
  MediaFile sse_decode_media_file(SseDeserializer deserializer);

  @protected
  MediaInfo sse_decode_media_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WatchProgress? sse_decode_opt_box_autoadd_watch_progress(
    SseDeserializer deserializer,
  );

  @protected
  QbitConfig sse_decode_qbit_config(SseDeserializer deserializer);

  @protected
  QbitTestResult sse_decode_qbit_test_result(SseDeserializer deserializer);

  @protected
  TmdbMatch sse_decode_tmdb_match(SseDeserializer deserializer);

  @protected
  TorrentInfo sse_decode_torrent_info(SseDeserializer deserializer);

  @protected
  Transaction sse_decode_transaction(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UndoBatchResult sse_decode_undo_batch_result(SseDeserializer deserializer);

  @protected
  UndoResult sse_decode_undo_result(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WatchProgress sse_decode_watch_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_config(Config self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_edit_request(
    EditRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qbit_config(
    QbitConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_watch_progress(
    WatchProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clear_result(ClearResult self, SseSerializer serializer);

  @protected
  void sse_encode_config(Config self, SseSerializer serializer);

  @protected
  void sse_encode_edit_request(EditRequest self, SseSerializer serializer);

  @protected
  void sse_encode_external_subtitle(
    ExternalSubtitle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_format_info(FormatInfo self, SseSerializer serializer);

  @protected
  void sse_encode_format_option(FormatOption self, SseSerializer serializer);

  @protected
  void sse_encode_genre_info(GenreInfo self, SseSerializer serializer);

  @protected
  void sse_encode_genre_page(GenrePage self, SseSerializer serializer);

  @protected
  void sse_encode_history_page(HistoryPage self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_external_subtitle(
    List<ExternalSubtitle> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_format_info(
    List<FormatInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_format_option(
    List<FormatOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_genre_info(
    List<GenreInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_file(
    List<MediaFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_info(
    List<MediaInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tmdb_match(
    List<TmdbMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_torrent_info(
    List<TorrentInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction(
    List<Transaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_watch_progress(
    List<WatchProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_detail(MediaDetail self, SseSerializer serializer);

  @protected
  void sse_encode_media_file(MediaFile self, SseSerializer serializer);

  @protected
  void sse_encode_media_info(MediaInfo self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_watch_progress(
    WatchProgress? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qbit_config(QbitConfig self, SseSerializer serializer);

  @protected
  void sse_encode_qbit_test_result(
    QbitTestResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tmdb_match(TmdbMatch self, SseSerializer serializer);

  @protected
  void sse_encode_torrent_info(TorrentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_transaction(Transaction self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_undo_batch_result(
    UndoBatchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_undo_result(UndoResult self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_watch_progress(WatchProgress self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
