// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A TMDb match for the review UI's picker.
class TmdbMatch {
  final BigInt tmdbId;
  final String title;
  final int? year;
  final String? posterUrl;
  final String mediaType;
  final String? overview;

  const TmdbMatch({
    required this.tmdbId,
    required this.title,
    this.year,
    this.posterUrl,
    required this.mediaType,
    this.overview,
  });

  @override
  int get hashCode =>
      tmdbId.hashCode ^
      title.hashCode ^
      year.hashCode ^
      posterUrl.hashCode ^
      mediaType.hashCode ^
      overview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TmdbMatch &&
          runtimeType == other.runtimeType &&
          tmdbId == other.tmdbId &&
          title == other.title &&
          year == other.year &&
          posterUrl == other.posterUrl &&
          mediaType == other.mediaType &&
          overview == other.overview;
}
