// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EditRequest {
  final String transactionId;
  final String title;
  final int? year;
  final String format;
  final String genre;
  final String mediaType;
  final BigInt? tmdbId;
  final String? posterUrl;
  final int? season;
  final int? episode;
  final String? episodeTitle;

  const EditRequest({
    required this.transactionId,
    required this.title,
    this.year,
    required this.format,
    required this.genre,
    required this.mediaType,
    this.tmdbId,
    this.posterUrl,
    this.season,
    this.episode,
    this.episodeTitle,
  });

  @override
  int get hashCode =>
      transactionId.hashCode ^
      title.hashCode ^
      year.hashCode ^
      format.hashCode ^
      genre.hashCode ^
      mediaType.hashCode ^
      tmdbId.hashCode ^
      posterUrl.hashCode ^
      season.hashCode ^
      episode.hashCode ^
      episodeTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditRequest &&
          runtimeType == other.runtimeType &&
          transactionId == other.transactionId &&
          title == other.title &&
          year == other.year &&
          format == other.format &&
          genre == other.genre &&
          mediaType == other.mediaType &&
          tmdbId == other.tmdbId &&
          posterUrl == other.posterUrl &&
          season == other.season &&
          episode == other.episode &&
          episodeTitle == other.episodeTitle;
}
