// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EditRequest {
  final String transactionId;
  final String title;
  final int? year;
  final String format;
  final String genre;
  final String mediaType;
  final BigInt? tmdbId;
  final String? posterUrl;
  final int? season;
  final int? episode;
  final String? episodeTitle;

  const EditRequest({
    required this.transactionId,
    required this.title,
    this.year,
    required this.format,
    required this.genre,
    required this.mediaType,
    this.tmdbId,
    this.posterUrl,
    this.season,
    this.episode,
    this.episodeTitle,
  });

  @override
  int get hashCode =>
      transactionId.hashCode ^
      title.hashCode ^
      year.hashCode ^
      format.hashCode ^
      genre.hashCode ^
      mediaType.hashCode ^
      tmdbId.hashCode ^
      posterUrl.hashCode ^
      season.hashCode ^
      episode.hashCode ^
      episodeTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditRequest &&
          runtimeType == other.runtimeType &&
          transactionId == other.transactionId &&
          title == other.title &&
          year == other.year &&
          format == other.format &&
          genre == other.genre &&
          mediaType == other.mediaType &&
          tmdbId == other.tmdbId &&
          posterUrl == other.posterUrl &&
          season == other.season &&
          episode == other.episode &&
          episodeTitle == other.episodeTitle;
}

class FormatInfo {
  final String name;
  final String path;
  final int genreCount;
  final int mediaCount;
  final List<String> posterSamples;

  const FormatInfo({
    required this.name,
    required this.path,
    required this.genreCount,
    required this.mediaCount,
    required this.posterSamples,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      genreCount.hashCode ^
      mediaCount.hashCode ^
      posterSamples.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          genreCount == other.genreCount &&
          mediaCount == other.mediaCount &&
          posterSamples == other.posterSamples;
}

class GenreInfo {
  final String name;
  final String path;
  final int mediaCount;
  final List<MediaInfo> mediaSamples;

  const GenreInfo({
    required this.name,
    required this.path,
    required this.mediaCount,
    required this.mediaSamples,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      mediaCount.hashCode ^
      mediaSamples.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenreInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          mediaCount == other.mediaCount &&
          mediaSamples == other.mediaSamples;
}

class GenrePage {
  final List<MediaInfo> items;
  final int total;
  final bool hasMore;

  const GenrePage({
    required this.items,
    required this.total,
    required this.hasMore,
  });

  @override
  int get hashCode => items.hashCode ^ total.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenrePage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          hasMore == other.hasMore;
}

class MediaDetail {
  final String title;
  final int? year;
  final String path;
  final String? posterUrl;
  final BigInt? tmdbId;
  final String format;
  final String genre;
  final String mediaType;
  final List<MediaFile> files;
  final int seasonCount;
  final int episodeCount;

  const MediaDetail({
    required this.title,
    this.year,
    required this.path,
    this.posterUrl,
    this.tmdbId,
    required this.format,
    required this.genre,
    required this.mediaType,
    required this.files,
    required this.seasonCount,
    required this.episodeCount,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      year.hashCode ^
      path.hashCode ^
      posterUrl.hashCode ^
      tmdbId.hashCode ^
      format.hashCode ^
      genre.hashCode ^
      mediaType.hashCode ^
      files.hashCode ^
      seasonCount.hashCode ^
      episodeCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaDetail &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          year == other.year &&
          path == other.path &&
          posterUrl == other.posterUrl &&
          tmdbId == other.tmdbId &&
          format == other.format &&
          genre == other.genre &&
          mediaType == other.mediaType &&
          files == other.files &&
          seasonCount == other.seasonCount &&
          episodeCount == other.episodeCount;
}

class MediaFile {
  final String path;
  final String filename;
  final int? season;
  final int? episode;
  final String? episodeTitle;
  final BigInt sizeBytes;
  final bool hasSubtitles;

  const MediaFile({
    required this.path,
    required this.filename,
    this.season,
    this.episode,
    this.episodeTitle,
    required this.sizeBytes,
    required this.hasSubtitles,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      filename.hashCode ^
      season.hashCode ^
      episode.hashCode ^
      episodeTitle.hashCode ^
      sizeBytes.hashCode ^
      hasSubtitles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          filename == other.filename &&
          season == other.season &&
          episode == other.episode &&
          episodeTitle == other.episodeTitle &&
          sizeBytes == other.sizeBytes &&
          hasSubtitles == other.hasSubtitles;
}

class MediaInfo {
  final String title;
  final int? year;
  final String path;
  final String? posterUrl;
  final BigInt? tmdbId;
  final String format;
  final String genre;

  const MediaInfo({
    required this.title,
    this.year,
    required this.path,
    this.posterUrl,
    this.tmdbId,
    required this.format,
    required this.genre,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      year.hashCode ^
      path.hashCode ^
      posterUrl.hashCode ^
      tmdbId.hashCode ^
      format.hashCode ^
      genre.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          year == other.year &&
          path == other.path &&
          posterUrl == other.posterUrl &&
          tmdbId == other.tmdbId &&
          format == other.format &&
          genre == other.genre;
}
