// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class QbitTestResult {
  final bool connected;
  final String version;
  final String message;

  const QbitTestResult({
    required this.connected,
    required this.version,
    required this.message,
  });

  @override
  int get hashCode => connected.hashCode ^ version.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QbitTestResult &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          version == other.version &&
          message == other.message;
}

class TorrentInfo {
  final String name;
  final String hash;
  final String savePath;
  final BigInt size;
  final List<String> files;

  const TorrentInfo({
    required this.name,
    required this.hash,
    required this.savePath,
    required this.size,
    required this.files,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      hash.hashCode ^
      savePath.hashCode ^
      size.hashCode ^
      files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          hash == other.hash &&
          savePath == other.savePath &&
          size == other.size &&
          files == other.files;
}
