// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class HistoryPage {
  final List<Transaction> items;
  final int total;
  final bool hasMore;

  const HistoryPage({
    required this.items,
    required this.total,
    required this.hasMore,
  });

  @override
  int get hashCode => items.hashCode ^ total.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          hasMore == other.hasMore;
}

class Transaction {
  final String id;
  final String batchId;
  final String sourcePath;
  final String destPath;
  final String title;
  final int? year;
  final String format;
  final String genre;
  final String mediaType;
  final int? season;
  final int? episode;
  final String? episodeTitle;
  final BigInt? tmdbId;
  final String? posterUrl;
  final String sha256;
  final String timestamp;
  final bool undone;
  final bool locked;
  final double confidence;

  const Transaction({
    required this.id,
    required this.batchId,
    required this.sourcePath,
    required this.destPath,
    required this.title,
    this.year,
    required this.format,
    required this.genre,
    required this.mediaType,
    this.season,
    this.episode,
    this.episodeTitle,
    this.tmdbId,
    this.posterUrl,
    required this.sha256,
    required this.timestamp,
    required this.undone,
    required this.locked,
    required this.confidence,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      batchId.hashCode ^
      sourcePath.hashCode ^
      destPath.hashCode ^
      title.hashCode ^
      year.hashCode ^
      format.hashCode ^
      genre.hashCode ^
      mediaType.hashCode ^
      season.hashCode ^
      episode.hashCode ^
      episodeTitle.hashCode ^
      tmdbId.hashCode ^
      posterUrl.hashCode ^
      sha256.hashCode ^
      timestamp.hashCode ^
      undone.hashCode ^
      locked.hashCode ^
      confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Transaction &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          batchId == other.batchId &&
          sourcePath == other.sourcePath &&
          destPath == other.destPath &&
          title == other.title &&
          year == other.year &&
          format == other.format &&
          genre == other.genre &&
          mediaType == other.mediaType &&
          season == other.season &&
          episode == other.episode &&
          episodeTitle == other.episodeTitle &&
          tmdbId == other.tmdbId &&
          posterUrl == other.posterUrl &&
          sha256 == other.sha256 &&
          timestamp == other.timestamp &&
          undone == other.undone &&
          locked == other.locked &&
          confidence == other.confidence;
}

class UndoBatchResult {
  final int total;
  final int succeeded;
  final int failed;

  const UndoBatchResult({
    required this.total,
    required this.succeeded,
    required this.failed,
  });

  @override
  int get hashCode => total.hashCode ^ succeeded.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UndoBatchResult &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          succeeded == other.succeeded &&
          failed == other.failed;
}

class UndoResult {
  final bool success;
  final String message;

  const UndoResult({required this.success, required this.message});

  @override
  int get hashCode => success.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UndoResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message;
}

class WatchProgress {
  final String filePath;
  final double positionSeconds;
  final double durationSeconds;
  final bool completed;
  final String lastWatched;
  final String? title;
  final String? posterUrl;
  final String? mediaPath;
  final int? season;
  final int? episode;
  final String? episodeTitle;
  final String? mediaType;

  const WatchProgress({
    required this.filePath,
    required this.positionSeconds,
    required this.durationSeconds,
    required this.completed,
    required this.lastWatched,
    this.title,
    this.posterUrl,
    this.mediaPath,
    this.season,
    this.episode,
    this.episodeTitle,
    this.mediaType,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      positionSeconds.hashCode ^
      durationSeconds.hashCode ^
      completed.hashCode ^
      lastWatched.hashCode ^
      title.hashCode ^
      posterUrl.hashCode ^
      mediaPath.hashCode ^
      season.hashCode ^
      episode.hashCode ^
      episodeTitle.hashCode ^
      mediaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WatchProgress &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          positionSeconds == other.positionSeconds &&
          durationSeconds == other.durationSeconds &&
          completed == other.completed &&
          lastWatched == other.lastWatched &&
          title == other.title &&
          posterUrl == other.posterUrl &&
          mediaPath == other.mediaPath &&
          season == other.season &&
          episode == other.episode &&
          episodeTitle == other.episodeTitle &&
          mediaType == other.mediaType;
}
