// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the AI classifier. Call once at startup (in background).
/// Will fail if the model file is not present at the expected path.
Future<void> initAi() => RustLib.instance.api.crateApiAiApiInitAi();

/// Check if the AI classifier is ready for use.
Future<bool> isAiReady() => RustLib.instance.api.crateApiAiApiIsAiReady();
