// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../config.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load config from disk (or return defaults if no file exists).
Future<Config> loadConfig() =>
    RustLib.instance.api.crateApiConfigApiLoadConfig();

/// Save config to disk.
Future<void> saveConfig({required Config cfg}) =>
    RustLib.instance.api.crateApiConfigApiSaveConfig(cfg: cfg);
