// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db/transactions.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get paginated transaction history.
Future<HistoryPage> getHistory({required int offset, required int limit}) =>
    RustLib.instance.api.crateApiHistoryApiGetHistory(
      offset: offset,
      limit: limit,
    );

/// Undo a single transaction (move file back to original location).
Future<UndoResult> undoTransaction({required String id}) =>
    RustLib.instance.api.crateApiHistoryApiUndoTransaction(id: id);

/// Undo an entire batch of transactions.
Future<UndoBatchResult> undoBatch({required String batchId}) =>
    RustLib.instance.api.crateApiHistoryApiUndoBatch(batchId: batchId);
