// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialization functions called once at app startup.
/// Initialize the database. Must be called before any transaction operations.
Future<void> initDb() => RustLib.instance.api.crateApiInitApiInitDb();

/// Simple ping to verify FFI bridge is alive.
Future<String> ping() => RustLib.instance.api.crateApiInitApiPing();
