// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../library.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get top-level format folders (Movies, Shows, Anime, etc.) from the library.
Future<List<FormatInfo>> getLibraryContents({required String libraryPath}) =>
    RustLib.instance.api.crateApiLibraryApiGetLibraryContents(
      libraryPath: libraryPath,
    );

/// Get genre folders within a format folder.
Future<List<GenreInfo>> getFormatContents({required String formatPath}) =>
    RustLib.instance.api.crateApiLibraryApiGetFormatContents(
      formatPath: formatPath,
    );

/// Get paginated media items within a genre folder.
Future<GenrePage> getGenreContents({
  required String genrePath,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiLibraryApiGetGenreContents(
  genrePath: genrePath,
  offset: offset,
  limit: limit,
);

/// Get detailed info about a single media item (movie or show folder).
Future<MediaDetail> getMediaDetails({required String mediaPath}) => RustLib
    .instance
    .api
    .crateApiLibraryApiGetMediaDetails(mediaPath: mediaPath);

/// Get recently added media from the library.
Future<List<MediaInfo>> getRecentlyAdded({
  required String libraryPath,
  required int limit,
}) => RustLib.instance.api.crateApiLibraryApiGetRecentlyAdded(
  libraryPath: libraryPath,
  limit: limit,
);
