// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../formats.dart';
import '../frb_generated.dart';
import '../metadata.dart';
import '../pipeline.dart';
import '../transaction.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `common_parent_of`

/// Process files in the background. Returns immediately.
/// Emits JSON-encoded progress events via StreamSink.
///
/// Event format (JSON):
/// - {"type":"started","total":N}
/// - {"type":"progress","done":N,"total":N,"title":"...","succeeded":N,"failed":N,"batch_id":"..."}
/// - {"type":"done","total":N,"succeeded":N,"failed":N,"batch_id":"..."}
Stream<String> processBackground({required List<String> paths}) =>
    RustLib.instance.api.crateApiPipelineApiProcessBackground(paths: paths);

/// Cancel any in-progress pipeline processing.
Future<void> cancelProcessing() =>
    RustLib.instance.api.crateApiPipelineApiCancelProcessing();

/// Reveal a file or folder in the system file manager.
Future<void> revealInFinder({required String path}) =>
    RustLib.instance.api.crateApiPipelineApiRevealInFinder(path: path);

/// Open a file with the system default application.
Future<void> openFile({required String path}) =>
    RustLib.instance.api.crateApiPipelineApiOpenFile(path: path);

/// Rescan the library -- fix misidentified files, download missing subtitles.
/// Emits progress events via StreamSink as JSON strings.
Stream<String> rescanLibrary() =>
    RustLib.instance.api.crateApiPipelineApiRescanLibrary();

/// Move entire library from one location to another.
Future<int> moveLibrary({required String fromPath, required String toPath}) =>
    RustLib.instance.api.crateApiPipelineApiMoveLibrary(
      fromPath: fromPath,
      toPath: toPath,
    );

/// Edit a transaction's metadata and relocate the file.
Future<Transaction> editAndRelocate({required EditRequest edit}) =>
    RustLib.instance.api.crateApiPipelineApiEditAndRelocate(edit: edit);

/// Search TMDb for matching media.
Future<List<TmdbMatch>> searchTmdbMulti({required String query, int? year}) =>
    RustLib.instance.api.crateApiPipelineApiSearchTmdbMulti(
      query: query,
      year: year,
    );

/// Get the list of available format options (Movies, Shows, Anime, etc.).
Future<List<FormatOption>> getFormatOptions() =>
    RustLib.instance.api.crateApiPipelineApiGetFormatOptions();
