// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db/watch_progress.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lang_code_to_name`

/// Save/update watch progress for a file.
Future<void> saveWatchProgress({
  required String filePath,
  required double position,
  required double duration,
  String? title,
  String? posterUrl,
  String? mediaPath,
  int? season,
  int? episode,
  String? episodeTitle,
  String? mediaType,
}) => RustLib.instance.api.crateApiPlaybackApiSaveWatchProgress(
  filePath: filePath,
  position: position,
  duration: duration,
  title: title,
  posterUrl: posterUrl,
  mediaPath: mediaPath,
  season: season,
  episode: episode,
  episodeTitle: episodeTitle,
  mediaType: mediaType,
);

/// Load watch progress for a single file.
Future<WatchProgress?> loadWatchProgress({required String filePath}) => RustLib
    .instance
    .api
    .crateApiPlaybackApiLoadWatchProgress(filePath: filePath);

/// Load all watch progress entries for a media (by media_path).
Future<List<WatchProgress>> loadAllProgress({required String mediaPath}) =>
    RustLib.instance.api.crateApiPlaybackApiLoadAllProgress(
      mediaPath: mediaPath,
    );

/// Mark a file as fully watched.
Future<void> setFileCompleted({required String filePath}) => RustLib
    .instance
    .api
    .crateApiPlaybackApiSetFileCompleted(filePath: filePath);

/// Mark a file as unwatched (remove progress).
Future<void> setFileUnwatched({required String filePath}) => RustLib
    .instance
    .api
    .crateApiPlaybackApiSetFileUnwatched(filePath: filePath);

/// Discover external subtitle files next to a video file.
/// Scans the video's parent directory and subdirectories for .srt, .ass, .ssa, .sub, .vtt files.
Future<List<ExternalSubtitle>> discoverExternalSubtitles({
  required String videoPath,
}) => RustLib.instance.api.crateApiPlaybackApiDiscoverExternalSubtitles(
  videoPath: videoPath,
);

/// An external subtitle file discovered next to a video.
class ExternalSubtitle {
  final String path;
  final String language;
  final String format;

  const ExternalSubtitle({
    required this.path,
    required this.language,
    required this.format,
  });

  @override
  int get hashCode => path.hashCode ^ language.hashCode ^ format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExternalSubtitle &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          language == other.language &&
          format == other.format;
}
