// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../config.dart';
import '../frb_generated.dart';
import '../qbittorrent.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Test qBittorrent connection with the given config.
Future<QbitTestResult> testQbittorrent({required QbitConfig qbitConfig}) =>
    RustLib.instance.api.crateApiQbitApiTestQbittorrent(qbitConfig: qbitConfig);

/// Auto-detect qBittorrent on common ports.
Future<QbitConfig> autoDetectQbittorrent() =>
    RustLib.instance.api.crateApiQbitApiAutoDetectQbittorrent();

/// Get list of completed torrents.
Future<List<TorrentInfo>> getCompletedTorrents() =>
    RustLib.instance.api.crateApiQbitApiGetCompletedTorrents();

/// Start the qBittorrent poller. Events emitted as JSON strings via StreamSink.
Stream<String> startQbitPoller() =>
    RustLib.instance.api.crateApiQbitApiStartQbitPoller();

/// Stop the qBittorrent poller.
Future<void> stopQbitPoller() =>
    RustLib.instance.api.crateApiQbitApiStopQbitPoller();

/// Check if the qBittorrent poller is running.
Future<bool> isQbitPollerRunning() =>
    RustLib.instance.api.crateApiQbitApiIsQbitPollerRunning();
