// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../transaction.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Get all unlocked (pending review) transactions for the given batch IDs.
Future<List<Transaction>> getReviewItems({required List<String> batchIds}) =>
    RustLib.instance.api.crateApiReviewApiGetReviewItems(batchIds: batchIds);

/// Get count of unlocked (pending review) transactions for the given batch IDs.
Future<int> getReviewCount({required List<String> batchIds}) =>
    RustLib.instance.api.crateApiReviewApiGetReviewCount(batchIds: batchIds);

/// Lock (approve) transactions -- they will no longer appear in review.
Future<int> lockTransactions({required List<String> ids}) =>
    RustLib.instance.api.crateApiReviewApiLockTransactions(ids: ids);

/// Undo all pending (unlocked) transactions. Returns (succeeded, failed).
Future<ClearResult> clearAllPending() =>
    RustLib.instance.api.crateApiReviewApiClearAllPending();

/// Result of clearing all pending reviews.
class ClearResult {
  final int succeeded;
  final int failed;

  const ClearResult({required this.succeeded, required this.failed});

  @override
  int get hashCode => succeeded.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClearResult &&
          runtimeType == other.runtimeType &&
          succeeded == other.succeeded &&
          failed == other.failed;
}
