// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../companion.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get all items in the trash bin.
Future<List<TrashItem>> getTrashItems() =>
    RustLib.instance.api.crateApiTrashApiGetTrashItems();

/// Restore a single trash item to its original location.
Future<String> restoreTrashItem({required String id}) =>
    RustLib.instance.api.crateApiTrashApiRestoreTrashItem(id: id);

/// Permanently delete a single trash item.
Future<void> deleteTrashItem({required String id}) =>
    RustLib.instance.api.crateApiTrashApiDeleteTrashItem(id: id);

/// Permanently delete all trash items.
Future<int> emptyTrash() => RustLib.instance.api.crateApiTrashApiEmptyTrash();

/// Get the number of items in the trash.
Future<int> getTrashCount() =>
    RustLib.instance.api.crateApiTrashApiGetTrashCount();
