// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Start the filesystem watcher. Events are emitted as JSON strings via StreamSink.
Stream<String> startWatcher() =>
    RustLib.instance.api.crateApiWatcherApiStartWatcher();

/// Stop the filesystem watcher.
Future<void> stopWatcher() =>
    RustLib.instance.api.crateApiWatcherApiStopWatcher();

/// Check if the watcher is currently running.
Future<bool> isWatcherRunning() =>
    RustLib.instance.api.crateApiWatcherApiIsWatcherRunning();
