// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class WatchProgress {
  final String filePath;
  final double positionSeconds;
  final double durationSeconds;
  final bool completed;
  final String lastWatched;
  final String? title;
  final String? posterUrl;
  final String? mediaPath;
  final int? season;
  final int? episode;
  final String? episodeTitle;
  final String? mediaType;

  const WatchProgress({
    required this.filePath,
    required this.positionSeconds,
    required this.durationSeconds,
    required this.completed,
    required this.lastWatched,
    this.title,
    this.posterUrl,
    this.mediaPath,
    this.season,
    this.episode,
    this.episodeTitle,
    this.mediaType,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      positionSeconds.hashCode ^
      durationSeconds.hashCode ^
      completed.hashCode ^
      lastWatched.hashCode ^
      title.hashCode ^
      posterUrl.hashCode ^
      mediaPath.hashCode ^
      season.hashCode ^
      episode.hashCode ^
      episodeTitle.hashCode ^
      mediaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WatchProgress &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          positionSeconds == other.positionSeconds &&
          durationSeconds == other.durationSeconds &&
          completed == other.completed &&
          lastWatched == other.lastWatched &&
          title == other.title &&
          posterUrl == other.posterUrl &&
          mediaPath == other.mediaPath &&
          season == other.season &&
          episode == other.episode &&
          episodeTitle == other.episodeTitle &&
          mediaType == other.mediaType;
}
